### ISSUE TITLE
Console tab complete doesn't work

### ISSUE THREAD

**Issue by Josh65-2201** [Moulberry/AxiomPaperPlugin#12]
## Description
I can't tab complete anything and instead the warning shows

## Logs
[error.txt](https://github.com/Moulberry/AxiomPaperPlugin/files/15443957/error.txt)

## Versions
Server: 1.20.1 Paper 198
Plugin: 1.5.11

**Comment by Moulberry** [comment]
Fixed in 2e3f3a1ae63de28b88d9a79d4d943a2c53f72e64
