### ISSUE TITLE
error with changing hotbars

### ISSUE THREAD

**Issue by Biielik** [Moulberry/AxiomPaperPlugin#14]
error message: Error while processing packet axiom:switch_active_hotbar: Cannot encode empty ItemStack

server logs: https://mclo.gs/r9SWRSo

**Comment by envizar** [comment]
same issue

**Comment by Taiyou06** [comment]
Can replicate it.

**Comment by SheharaVinod** [comment]
yeah me too , hot bar not changed ,but look like changed, but its not changed

**Comment by envizar** [comment]
> yeah me too , hot bar not changed ,but look like changed, but its not changed

can't reproduce
Axiom 3.1.0, Axiom Paper Plugin 1.5+ (rev.12), Paper build 38 for mc 1.21
