### ISSUE TITLE
[BUG] Unable to load the plugin

### ISSUE THREAD

**Issue by v38armageddon** [Moulberry/AxiomPaperPlugin#16]
## Description
One of my friends talk about the mod, wanted to install it to see what's can offer to us and the plugin cannot be loaded.

## Steps to reproduce
1. Download the .jar file
2. Put into the ``plugins`` folder
3. Start the server

## Screenshot
![image](https://github.com/Moulberry/AxiomPaperPlugin/assets/69727502/a64f1e8c-362b-4bc2-962e-d38427f2de30)

## System info
- OS: ArchLinux
- Kernel: 6.9.4-hardened1-1-hardened
- Minecraft Server type: Purpur
- MC Version: 1.20.4
- Server version: purpur-1.20.4-2174
- Axiom version: 3.0.0

## Logs
Full logs available here: https://gist.github.com/v38armageddon/7ad1ccf6dfa3a9723c2e09badcc0cb52

**Comment by TWME-TW** [comment]
> ## Description
> One of my friends talk about the mod, wanted to install it to see what's can offer to us and the plugin cannot be loaded.
> 
> ## Steps to reproduce
> 1. Download the .jar file
> 2. Put into the `plugins` folder
> 3. Start the server
> 4. See error
> 
> ## Screenshot
> ![image](https://private-user-images.githubusercontent.com/69727502/340424953-a64f1e8c-362b-4bc2-962e-d38427f2de30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4ODIxNzAsIm5iZiI6MTcxODg4MTg3MCwicGF0aCI6Ii82OTcyNzUwMi8zNDA0MjQ5NTMtYTY0ZjFlOGMtMzYyYi00YmMyLTk2MmUtZDM4NDI3ZjJkZTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDExMTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNTdkMTBkYjUwNGMyMzdiNTE0NTE4Y2I4YzBlYjE3M2ZmYWY5NjYwMDUwNmVjOWU0YzNiM2Q5NDBhMDQwZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ojJD0nKcFTsWXK9Ok8nj_0tCjK0y6v-BTmGSNI5sWfo)
> 
> ## System info
> * OS: ArchLinux
> * Kernel: 6.9.4-hardened1-1-hardened
> * Minecraft Server type: Purpur
> * MC Version: 1.20.4
> * Server version: purpur-1.20.4-2174
> * Axiom version: 3.0.0
> 
> ## Logs
> Full logs available here: https://gist.github.com/v38armageddon/7ad1ccf6dfa3a9723c2e09badcc0cb52

You should install AxiomPaper, not Axiom itself
https://modrinth.com/plugin/axiom-paper-plugin

**Comment by v38armageddon** [comment]
> You should install AxiomPaper, not Axiom itself https://modrinth.com/plugin/axiom-paper-plugin

Thanks! With the plugin, this works like a charm!
