### ISSUE TITLE
Aternos problem

### ISSUE THREAD

**Issue by Biielik** [Moulberry/AxiomPaperPlugin#20]
I couldn't make axiom thru plugin work on aternos hosting.
It says the server doesn't support it.
I tried asking them for help, but they didn't know either

video**: https://drive.google.com/file/d/1eQ4AJjW--selLoK3nmmo95NItadL9Kfx/view
logs: https://mclo.gs/j7YA0Ay

PS. I tested new server and client too
** I know this is linux, but on windows its the same problem

**Comment by TWME-TW** [comment]
> I couldn't make axiom thru plugin work on aternos hosting. It says the server doesn't support it. I tried asking them for help, but they didn't know either
> 
> video**: https://drive.google.com/file/d/1eQ4AJjW--selLoK3nmmo95NItadL9Kfx/view logs: https://mclo.gs/j7YA0Ay
> 
> PS. I tested new server and client too ** I know this is linux, but on windows its the same problem

Please check if you have the correct permissions or OP. NOTE: Using Axiom on a private server requires a commercial license or whitelist

**Comment by Biielik** [comment]
Yes, I have the operator status
