### ISSUE TITLE
[Bug ?] AxiomPaper doesn't load/work on a 1.21 (Paper) Server

### ISSUE THREAD

**Issue by Immersiiv** [Moulberry/AxiomPaperPlugin#23]
In game, my server is on 1.21 server. I have AxiomPaper on version v1.5.12 for "Paper 1.21" but he's doesn't load/work with crash report :  

![VersionofAxiomPaper](https://github.com/user-attachments/assets/f55ee3ec-68e6-45e1-a87f-33a9c734e1d8)

![crash-report](https://github.com/user-attachments/assets/433a54e4-aae3-4d88-83e8-2e6b6fbd841d)

My plugins enabled on my server ? If the problem is inside ?
![list-plugins](https://github.com/user-attachments/assets/50f45b0e-0c5f-425f-8c33-19cca938f0c7)

**Comment by anmvc** [comment]
1.21.1 issue
