### ISSUE TITLE
Unable to use Biome Painter tool on PlotSquared plots without admin-only permission

### ISSUE THREAD

**Issue by Feniksovich** [Moulberry/AxiomPaperPlugin#9]
### To Reproduce
1. Claim P2 plot with `/p auto` or `/p claim`.
2. Make sure you have only all needed AxiomPaper permissions or `axiom.*`.
3. Select Biome Painter tool and try to paint on the plot.
4. Receive message about the need for the P2 admin-only permission `plots.admin.build.other`.

### Demo
https://pixeldrain.com/api/file/jT4cTzTB

### Tech Info
– Paper 1.20.4 build 2176
– Axiom 2.8.1
– AxiomPaper 1.5.9
– PlotSquared 7.3.3

**Comment by Moulberry** [comment]
This should have been fixed in Axiom Paper 1.5.11, you are using an outdated version
